<<<<<<< HEAD
name: 01 Building Blocks

on : push

jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: "first in steps"
        run : echo "hello first step"

      - name : "second in steps"
        run: |
          echo "this is multiple runs"
          echo "this is second run"
  
  second job:
    runs-on: ubuntu-latest
    steps:
      - name : failed step
        run: echo "fail"
             exit 1
=======
name: 01 - Building Blocks

on: workflow_dispatch

jobs:
  echo-sharath: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo Sharath
        run: echo "Sharath"

  echo-Arpitha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Arpitha
        run: |
          echo "arpitha"
          exit 1 

      - name: Echo Test
        # if: ${{ failure() }}
        run: echo "skip this step runs only if the previous step fails."
>>>>>>> 3b823c0e697186be0406a97c7babfd77f1c354c5
