name: 01 Building Blocks

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello this is my first job"
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "Just in this step"
          exit 0

      - name: Good Bye
        run: echo "Good Bye!!!"