name: 01 Building Blocks

on : push


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello Sharu"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goo bye
        run: |
          echo "i will fail"
          exit 1
      - name: verify this step
        run: |
          echo "hello gh-actions"

