name: 01 Building Blocks

on : push

jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: "first in steps"
        run : echo "hello first step"

      - name : "second in steps"
        run: |
          echo "this is multiple runs"
          echo "this is second run"
  
  second job:
    runs-on: ubuntu-latest
    steps:
      - name : failed step
        run: echo "fail"
             exit 1