name : 02 workflow events

on : push

jobs:
  hello-world1:
    runs-on: ubuntu-latest
    steps:
      - name: This step is to display the trigger name
        run: echo "Please display the trigger name/event name: ${{ github.event_name}}"
