name : 02 workflow events

on:
  # push:
  # pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *' 
  #   - cron: '*/5 * * * *'
  

jobs:
  hello-world1:
    runs-on: ubuntu-latest
    steps:
      - name: This step is to display the trigger name
        run: echo "i've been triggered by an event:" "${{ github.event_name}}"
